// ─── AWQ Asset Layer — BU Subledger Snapshot Data · Q1 2026 ──────────────────
//
// CLASSIFICATION: snapshot / planning data — registered in lib/snapshot-registry.ts
// PERIOD: Q1 2026 (Jan–Mar 2026 — frozen snapshot)
// SOURCE: manually curated asset register per BU.
//
// ARCHITECTURE RULE:
//   Each BU has its own subledger (BuAssetSubledger). The holding reads ONLY the
//   BuAssetSnapshot derived from each subledger by asset-query.ts. The holding
//   CANNOT modify individual asset records — it only receives, consolidates, governs.
//
//   strategic_non_recognized assets are tracked for context but are NEVER added
//   to consolidated equity figures. They appear only in /awq/assets/strategic.
//
// DO NOT import this file directly in pages — use lib/asset-query.ts instead.
// DO NOT add new assets here without a snapshot-registry.ts entry.

import type { BuAssetSubledger, AssetRecord, AssetMovement } from "./asset-types";

// ─── Q1 2026 reference date ──────────────────────────────────────────────────
const SNAP = "2026-03-31";
const PERIOD = "2026-Q1";

// ─── JACQES Subledger ─────────────────────────────────────────────────────────

const jacqesAssets: AssetRecord[] = [
  {
    "asset_id": "JAQ-TAN-001",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Laptops MacBook Pro 14\" (x28)",
    "asset_type": "tangible",
    "asset_class": "equipment_computing",
    "asset_subclass": "Apple MacBook Pro 14\" M3",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "Head de Operações JACQES",
    "acquisition_date": "2023-01-15",
    "activation_date": "2023-01-20",
    "acquisition_cost": 280000,
    "replacement_cost": 310000,
    "residual_value": 28000,
    "useful_life_months": 48,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 5250,
    "monthly_amortization": 0,
    "gross_book_value": 280000,
    "accumulated_depreciation": 199500,
    "accumulated_amortization": 0,
    "carrying_value": 80500,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Escritório JACQES — São Paulo / Remoto",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio JACQES",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Head de Operações JACQES",
    "last_review_date": "2025-10-01",
    "next_review_date": "2026-10-01",
    "notes": "28 laptops corporativos, 1 por colaborador. NF disponível."
  },
  {
    "asset_id": "JAQ-TAN-002",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Mobiliário de Escritório",
    "asset_type": "tangible",
    "asset_class": "furniture_fixtures",
    "asset_subclass": "Mesas, cadeiras ergonômicas, armários",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "Head de Operações JACQES",
    "acquisition_date": "2021-06-01",
    "activation_date": "2021-06-15",
    "acquisition_cost": 45000,
    "replacement_cost": 55000,
    "residual_value": 4500,
    "useful_life_months": 120,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 338,
    "monthly_amortization": 0,
    "gross_book_value": 45000,
    "accumulated_depreciation": 19238,
    "accumulated_amortization": 0,
    "carrying_value": 25762,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Escritório JACQES — São Paulo",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio JACQES",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Head de Operações JACQES",
    "last_review_date": "2025-06-01",
    "next_review_date": "2026-06-01",
    "notes": "Mobiliário sede São Paulo. NF de compra arquivada."
  },
  {
    "asset_id": "JAQ-TAN-003",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Equipamento AV e Videoconferência",
    "asset_type": "tangible",
    "asset_class": "equipment_audio_visual",
    "asset_subclass": "Monitores 4K, câmeras Logitech, caixas de som",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "Head de Operações JACQES",
    "acquisition_date": "2022-03-01",
    "activation_date": "2022-03-15",
    "acquisition_cost": 38000,
    "replacement_cost": 42000,
    "residual_value": 3800,
    "useful_life_months": 60,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 570,
    "monthly_amortization": 0,
    "gross_book_value": 38000,
    "accumulated_depreciation": 27360,
    "accumulated_amortization": 0,
    "carrying_value": 10640,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Escritório JACQES — São Paulo",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio JACQES",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Head de Operações JACQES",
    "last_review_date": "2025-03-01",
    "next_review_date": "2026-03-01",
    "notes": "Equipamento de reuniões e apresentações."
  },
  {
    "asset_id": "JAQ-TAN-004",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Dispositivos Móveis (x28)",
    "asset_type": "tangible",
    "asset_class": "equipment_mobile",
    "asset_subclass": "iPhone + iPad por colaborador",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "Head de Operações JACQES",
    "acquisition_date": "2023-09-01",
    "activation_date": "2023-09-05",
    "acquisition_cost": 42000,
    "replacement_cost": 48000,
    "residual_value": 0,
    "useful_life_months": 36,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 1167,
    "monthly_amortization": 0,
    "gross_book_value": 42000,
    "accumulated_depreciation": 35010,
    "accumulated_amortization": 0,
    "carrying_value": 6990,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Distribuído — colaboradores JACQES",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio JACQES",
    "allocation_rule": null,
    "documentation_status": "partial",
    "evidence_level": "medium",
    "valuation_confidence": "probable",
    "review_owner": "Head de Operações JACQES",
    "last_review_date": "2025-09-01",
    "next_review_date": "2026-03-01",
    "notes": "NF parcialmente arquivada. Revisão de inventário pendente."
  },
  {
    "asset_id": "JAQ-INT-001",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Carteira de Clientes — Direitos Contratuais",
    "asset_type": "intangible_recognized",
    "asset_class": "client_portfolio",
    "asset_subclass": "Contratos de serviço de longo prazo (10 clientes)",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "CEO JACQES",
    "acquisition_date": "2024-01-01",
    "activation_date": "2024-01-01",
    "acquisition_cost": 500000,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 36,
    "depreciation_method": "not_applicable",
    "amortization_method": "straight_line",
    "monthly_depreciation": 0,
    "monthly_amortization": 13889,
    "gross_book_value": 500000,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 361114,
    "carrying_value": 138886,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Jurídico JACQES",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio JACQES",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "CEO JACQES",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-07-01",
    "notes": "Contratos ativos com 10 clientes recorrentes. Amortização linear 36 meses."
  },
  {
    "asset_id": "JAQ-INT-002",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Licenças de Software (Adobe CC, Figma, Slack)",
    "asset_type": "intangible_recognized",
    "asset_class": "software_license",
    "asset_subclass": "Licenças anuais prepagadas — equipe criativa",
    "recognition_type": "recognized",
    "ownership_type": "licensed",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "Head de Tecnologia JACQES",
    "acquisition_date": "2025-09-01",
    "activation_date": "2025-09-01",
    "acquisition_cost": 68000,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 12,
    "depreciation_method": "not_applicable",
    "amortization_method": "straight_line",
    "monthly_depreciation": 0,
    "monthly_amortization": 5667,
    "gross_book_value": 68000,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 34002,
    "carrying_value": 33998,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Nuvem / Distribuído",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio JACQES",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Head de Tecnologia JACQES",
    "last_review_date": "2026-01-15",
    "next_review_date": "2026-09-01",
    "notes": "Renováveis anualmente. Próxima renovação set/2026."
  },
  {
    "asset_id": "JAQ-STR-001",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Marca JACQES — Brand Equity",
    "asset_type": "strategic_non_recognized",
    "asset_class": "brand_equity",
    "asset_subclass": "Reputação de marca no mercado criativo brasileiro",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "CEO JACQES",
    "acquisition_date": "2018-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Construção orgânica",
    "allocation_rule": null,
    "documentation_status": "missing",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "CEO JACQES",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Não reconhecido contabilmente. Relevante para valuation de M&A. Estimativa não auditada."
  },
  {
    "asset_id": "JAQ-STR-002",
    "holding_id": "AWQ",
    "bu_id": "jacqes",
    "asset_name": "Metodologia Criativa Proprietária",
    "asset_type": "strategic_non_recognized",
    "asset_class": "creative_methodology",
    "asset_subclass": "Framework de entrega de campanhas e conteúdo",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "JACQES Agência Ltda",
    "custodian_responsible": "CCO JACQES",
    "acquisition_date": "2020-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Desenvolvimento interno",
    "allocation_rule": null,
    "documentation_status": "partial",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "CCO JACQES",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Não reconhecido contabilmente. Documentação interna em elaboração."
  }
];

// ─── Caza Vision Subledger ────────────────────────────────────────────────────

const cazaAssets: AssetRecord[] = [
  {
    "asset_id": "CAZ-TAN-001",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Kit de Câmeras Cinema (ARRI + Sony FX)",
    "asset_type": "tangible",
    "asset_class": "equipment_production",
    "asset_subclass": "ARRI Mini LF + Sony FX9 + acessórios",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "Diretor de Fotografia Caza",
    "acquisition_date": "2022-06-01",
    "activation_date": "2022-06-15",
    "acquisition_cost": 420000,
    "replacement_cost": 480000,
    "residual_value": 42000,
    "useful_life_months": 60,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 6300,
    "monthly_amortization": 0,
    "gross_book_value": 420000,
    "accumulated_depreciation": 264600,
    "accumulated_amortization": 0,
    "carrying_value": 155400,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Studio Caza Vision — São Paulo",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Caza Vision",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Diretor de Fotografia Caza",
    "last_review_date": "2026-01-15",
    "next_review_date": "2026-07-15",
    "notes": "Kit principal de produção. NFs e laudos de seguro arquivados."
  },
  {
    "asset_id": "CAZ-TAN-002",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Equipamento de Iluminação Profissional",
    "asset_type": "tangible",
    "asset_class": "equipment_production",
    "asset_subclass": "Arri Skypanel, HMIs, grip, caixões",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "Gaffer Caza",
    "acquisition_date": "2021-09-01",
    "activation_date": "2021-09-15",
    "acquisition_cost": 180000,
    "replacement_cost": 210000,
    "residual_value": 18000,
    "useful_life_months": 84,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 1929,
    "monthly_amortization": 0,
    "gross_book_value": 180000,
    "accumulated_depreciation": 105087,
    "accumulated_amortization": 0,
    "carrying_value": 74913,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Studio Caza Vision — São Paulo",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Caza Vision",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Gaffer Caza",
    "last_review_date": "2025-09-01",
    "next_review_date": "2026-09-01",
    "notes": "Kit de iluminação completo, incluindo gelatinas e difusores."
  },
  {
    "asset_id": "CAZ-TAN-003",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Drones (DJI Inspire 3 + DJI Mavic 3)",
    "asset_type": "tangible",
    "asset_class": "equipment_production",
    "asset_subclass": "DJI Inspire 3 + DJI Mavic 3 Cine + licenças ANAC",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "Piloto Certificado Caza",
    "acquisition_date": "2023-04-01",
    "activation_date": "2023-04-15",
    "acquisition_cost": 95000,
    "replacement_cost": 110000,
    "residual_value": 9500,
    "useful_life_months": 36,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 2375,
    "monthly_amortization": 0,
    "gross_book_value": 95000,
    "accumulated_depreciation": 71250,
    "accumulated_amortization": 0,
    "carrying_value": 23750,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Studio Caza Vision — São Paulo",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Caza Vision",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Piloto Certificado Caza",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-07-01",
    "notes": "Licenças ANAC ativas até 2027. Segurado."
  },
  {
    "asset_id": "CAZ-TAN-004",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Workstations de Edição (Mac Pro x5)",
    "asset_type": "tangible",
    "asset_class": "equipment_computing",
    "asset_subclass": "Apple Mac Pro M2 Ultra + monitores Pro Display XDR",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "Head de Pós-Produção Caza",
    "acquisition_date": "2023-08-01",
    "activation_date": "2023-08-10",
    "acquisition_cost": 125000,
    "replacement_cost": 140000,
    "residual_value": 12500,
    "useful_life_months": 60,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 1875,
    "monthly_amortization": 0,
    "gross_book_value": 125000,
    "accumulated_depreciation": 56250,
    "accumulated_amortization": 0,
    "carrying_value": 68750,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Sala de Pós-Produção — Studio Caza",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Caza Vision",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Head de Pós-Produção Caza",
    "last_review_date": "2026-01-15",
    "next_review_date": "2026-07-15",
    "notes": "Estações de edição principal + finalização de cor."
  },
  {
    "asset_id": "CAZ-TAN-005",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Infraestrutura de Armazenamento (NAS + RAID)",
    "asset_type": "tangible",
    "asset_class": "infrastructure",
    "asset_subclass": "QNAP NAS 200TB + RAID Thunderbolt backups",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "Head de Pós-Produção Caza",
    "acquisition_date": "2023-01-01",
    "activation_date": "2023-01-15",
    "acquisition_cost": 48000,
    "replacement_cost": 55000,
    "residual_value": 0,
    "useful_life_months": 48,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 1000,
    "monthly_amortization": 0,
    "gross_book_value": 48000,
    "accumulated_depreciation": 38000,
    "accumulated_amortization": 0,
    "carrying_value": 10000,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Sala de Servidores — Studio Caza",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Caza Vision",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Head de Pós-Produção Caza",
    "last_review_date": "2025-07-01",
    "next_review_date": "2026-07-01",
    "notes": "Storage on-premise para projetos ativos e arquivo."
  },
  {
    "asset_id": "CAZ-INT-001",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "IP de Conteúdo — Biblioteca de Filmes Produzidos",
    "asset_type": "intangible_recognized",
    "asset_class": "intellectual_property",
    "asset_subclass": "Direitos de propriedade intelectual — produções 2021-2025",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "CEO Caza Vision",
    "acquisition_date": "2022-01-01",
    "activation_date": "2022-01-01",
    "acquisition_cost": 320000,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 60,
    "depreciation_method": "not_applicable",
    "amortization_method": "straight_line",
    "monthly_depreciation": 0,
    "monthly_amortization": 5333,
    "gross_book_value": 320000,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 277316,
    "carrying_value": 42684,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Jurídico Caza Vision",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Caza Vision",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "CEO Caza Vision",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-07-01",
    "notes": "IP de produções entregues com retenção de direitos. Contratos arquivados."
  },
  {
    "asset_id": "CAZ-INT-002",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Licenças DaVinci Resolve Studio + Adobe CC",
    "asset_type": "intangible_recognized",
    "asset_class": "software_license",
    "asset_subclass": "Licenças de pós-produção e motion graphics",
    "recognition_type": "recognized",
    "ownership_type": "licensed",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "Head de Pós-Produção Caza",
    "acquisition_date": "2025-07-01",
    "activation_date": "2025-07-01",
    "acquisition_cost": 42000,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 12,
    "depreciation_method": "not_applicable",
    "amortization_method": "straight_line",
    "monthly_depreciation": 0,
    "monthly_amortization": 3500,
    "gross_book_value": 42000,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 31500,
    "carrying_value": 10500,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Nuvem / Workstations locais",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Caza Vision",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Head de Pós-Produção Caza",
    "last_review_date": "2026-01-15",
    "next_review_date": "2026-07-01",
    "notes": "Licenças anuais. Renovação jul/2026."
  },
  {
    "asset_id": "CAZ-STR-001",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Marca Caza Vision — Reputação de Produtora",
    "asset_type": "strategic_non_recognized",
    "asset_class": "brand_equity",
    "asset_subclass": "Posicionamento e reputação no mercado audiovisual",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "CEO Caza Vision",
    "acquisition_date": "2019-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Construção orgânica",
    "allocation_rule": null,
    "documentation_status": "missing",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "CEO Caza Vision",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Não reconhecido contabilmente. Portfolio de clientes e premiações são proxy de valor."
  },
  {
    "asset_id": "CAZ-STR-002",
    "holding_id": "AWQ",
    "bu_id": "caza",
    "asset_name": "Rede de Diretores e Talentos Criativos",
    "asset_type": "strategic_non_recognized",
    "asset_class": "network_value",
    "asset_subclass": "Relacionamentos com diretores, atores e fornecedores especializados",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "Caza Vision Produtora Ltda",
    "custodian_responsible": "CEO Caza Vision",
    "acquisition_date": "2019-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Desenvolvimento interno",
    "allocation_rule": null,
    "documentation_status": "missing",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "CEO Caza Vision",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Capital relacional. Crítico para pipeline de projetos premium."
  }
];

// ─── Advisor Subledger ────────────────────────────────────────────────────────

const advisorAssets: AssetRecord[] = [
  {
    "asset_id": "ADV-TAN-001",
    "holding_id": "AWQ",
    "bu_id": "advisor",
    "asset_name": "Laptops MacBook Air (x8)",
    "asset_type": "tangible",
    "asset_class": "equipment_computing",
    "asset_subclass": "Apple MacBook Air M2 — 1 por consultor",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Advisor Consultoria Ltda",
    "custodian_responsible": "Sócio Gestor Advisor",
    "acquisition_date": "2023-03-01",
    "activation_date": "2023-03-05",
    "acquisition_cost": 80000,
    "replacement_cost": 90000,
    "residual_value": 8000,
    "useful_life_months": 48,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 1500,
    "monthly_amortization": 0,
    "gross_book_value": 80000,
    "accumulated_depreciation": 54000,
    "accumulated_amortization": 0,
    "carrying_value": 26000,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Distribuído — consultores Advisor",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Advisor",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Sócio Gestor Advisor",
    "last_review_date": "2025-09-01",
    "next_review_date": "2026-09-01",
    "notes": "NFs arquivadas. 1 unidade em manutenção preventiva."
  },
  {
    "asset_id": "ADV-TAN-002",
    "holding_id": "AWQ",
    "bu_id": "advisor",
    "asset_name": "Mobiliário de Escritório — Sala de Reuniões",
    "asset_type": "tangible",
    "asset_class": "furniture_fixtures",
    "asset_subclass": "Mesa de reunião, cadeiras, aparador",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Advisor Consultoria Ltda",
    "custodian_responsible": "Sócio Gestor Advisor",
    "acquisition_date": "2021-01-01",
    "activation_date": "2021-01-15",
    "acquisition_cost": 18000,
    "replacement_cost": 22000,
    "residual_value": 1800,
    "useful_life_months": 120,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 135,
    "monthly_amortization": 0,
    "gross_book_value": 18000,
    "accumulated_depreciation": 8370,
    "accumulated_amortization": 0,
    "carrying_value": 9630,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Escritório Advisor — São Paulo",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Advisor",
    "allocation_rule": null,
    "documentation_status": "partial",
    "evidence_level": "medium",
    "valuation_confidence": "probable",
    "review_owner": "Sócio Gestor Advisor",
    "last_review_date": "2025-01-01",
    "next_review_date": "2026-01-01",
    "notes": "NF original extraviada. Estimativa baseada em cotação de reposição."
  },
  {
    "asset_id": "ADV-INT-001",
    "holding_id": "AWQ",
    "bu_id": "advisor",
    "asset_name": "Contratos de Consultoria de Longo Prazo (30 clientes)",
    "asset_type": "intangible_recognized",
    "asset_class": "contract_rights",
    "asset_subclass": "Contratos plurianuais de advisory e gestão",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Advisor Consultoria Ltda",
    "custodian_responsible": "Sócio Gestor Advisor",
    "acquisition_date": "2024-06-01",
    "activation_date": "2024-06-01",
    "acquisition_cost": 450000,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 24,
    "depreciation_method": "not_applicable",
    "amortization_method": "straight_line",
    "monthly_depreciation": 0,
    "monthly_amortization": 18750,
    "gross_book_value": 450000,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 187500,
    "carrying_value": 262500,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Jurídico Advisor",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Advisor",
    "allocation_rule": null,
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Sócio Gestor Advisor",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-06-01",
    "notes": "Base contratual de 30 clientes ativos. Renovações em andamento."
  },
  {
    "asset_id": "ADV-INT-002",
    "holding_id": "AWQ",
    "bu_id": "advisor",
    "asset_name": "Framework de Diagnóstico Estratégico",
    "asset_type": "intangible_recognized",
    "asset_class": "intellectual_property",
    "asset_subclass": "Metodologia proprietária de diagnóstico e roadmap",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "Advisor Consultoria Ltda",
    "custodian_responsible": "Sócio Gestor Advisor",
    "acquisition_date": "2022-01-01",
    "activation_date": "2022-01-01",
    "acquisition_cost": 150000,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 60,
    "depreciation_method": "not_applicable",
    "amortization_method": "straight_line",
    "monthly_depreciation": 0,
    "monthly_amortization": 2500,
    "gross_book_value": 150000,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 125000,
    "carrying_value": 25000,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Documentação interna Advisor",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital próprio Advisor",
    "allocation_rule": null,
    "documentation_status": "partial",
    "evidence_level": "medium",
    "valuation_confidence": "probable",
    "review_owner": "Sócio Gestor Advisor",
    "last_review_date": "2025-06-01",
    "next_review_date": "2026-06-01",
    "notes": "Metodologia em uso ativo. Documentação formal em elaboração."
  },
  {
    "asset_id": "ADV-STR-001",
    "holding_id": "AWQ",
    "bu_id": "advisor",
    "asset_name": "Rede de Parceiros e Indicações (Network Advisor)",
    "asset_type": "strategic_non_recognized",
    "asset_class": "network_value",
    "asset_subclass": "Relacionamentos com C-level, VCs e advisors setoriais",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "Advisor Consultoria Ltda",
    "custodian_responsible": "Sócio Gestor Advisor",
    "acquisition_date": "2018-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": true,
    "is_shared_with_other_bus": false,
    "funding_source": "Construção orgânica",
    "allocation_rule": "70% Advisor / 30% AWQ Holding (uso em deal sourcing do grupo)",
    "documentation_status": "missing",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "Sócio Gestor Advisor",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Compartilhado com AWQ Holding para deal sourcing. Regra de alocação formalizada."
  },
  {
    "asset_id": "ADV-STR-002",
    "holding_id": "AWQ",
    "bu_id": "advisor",
    "asset_name": "Modelos Analíticos Proprietários",
    "asset_type": "strategic_non_recognized",
    "asset_class": "proprietary_model",
    "asset_subclass": "Modelos de valuation, pricing e análise de viabilidade",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "Advisor Consultoria Ltda",
    "custodian_responsible": "Sócio Gestor Advisor",
    "acquisition_date": "2020-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Desenvolvimento interno",
    "allocation_rule": null,
    "documentation_status": "partial",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "Sócio Gestor Advisor",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Modelos em uso ativo em mandatos de advisory."
  }
];

// ─── AWQ Venture Subledger ────────────────────────────────────────────────────

const ventureAssets: AssetRecord[] = [
  {
    "asset_id": "VEN-TAN-001",
    "holding_id": "AWQ",
    "bu_id": "venture",
    "asset_name": "Laptops MacBook Air (x3)",
    "asset_type": "tangible",
    "asset_class": "equipment_computing",
    "asset_subclass": "Apple MacBook Air M2",
    "recognition_type": "recognized",
    "ownership_type": "owned",
    "owner_entity": "AWQ Venture Investimentos",
    "custodian_responsible": "Gestor AWQ Venture",
    "acquisition_date": "2024-01-01",
    "activation_date": "2024-01-05",
    "acquisition_cost": 30000,
    "replacement_cost": 33000,
    "residual_value": 3000,
    "useful_life_months": 48,
    "depreciation_method": "straight_line",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 563,
    "monthly_amortization": 0,
    "gross_book_value": 30000,
    "accumulated_depreciation": 8445,
    "accumulated_amortization": 0,
    "carrying_value": 21555,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Distribuído — equipe AWQ Venture",
    "is_shared_with_holding": true,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital AWQ Venture",
    "allocation_rule": "100% AWQ Venture (uso exclusivo equipe venture)",
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Gestor AWQ Venture",
    "last_review_date": "2025-07-01",
    "next_review_date": "2026-07-01",
    "notes": "NFs arquivadas. Compartilhamento com holding declarado mas uso exclusivo venture."
  },
  {
    "asset_id": "VEN-INT-001",
    "holding_id": "AWQ",
    "bu_id": "venture",
    "asset_name": "Plataforma de Gestão de Portfolio (Software)",
    "asset_type": "intangible_recognized",
    "asset_class": "software_license",
    "asset_subclass": "SaaS de portfolio management e deal tracking",
    "recognition_type": "recognized",
    "ownership_type": "licensed",
    "owner_entity": "AWQ Venture Investimentos",
    "custodian_responsible": "Gestor AWQ Venture",
    "acquisition_date": "2024-04-01",
    "activation_date": "2024-04-01",
    "acquisition_cost": 45000,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 36,
    "depreciation_method": "not_applicable",
    "amortization_method": "straight_line",
    "monthly_depreciation": 0,
    "monthly_amortization": 1250,
    "gross_book_value": 45000,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 13750,
    "carrying_value": 31250,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Nuvem",
    "is_shared_with_holding": true,
    "is_shared_with_other_bus": false,
    "funding_source": "Capital AWQ Venture",
    "allocation_rule": "80% AWQ Venture / 20% AWQ Holding (acesso de monitoramento)",
    "documentation_status": "complete",
    "evidence_level": "high",
    "valuation_confidence": "confirmed",
    "review_owner": "Gestor AWQ Venture",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-07-01",
    "notes": "Compartilhado com holding para monitoramento de portfolio. Regra de alocação formalizada."
  },
  {
    "asset_id": "VEN-STR-001",
    "holding_id": "AWQ",
    "bu_id": "venture",
    "asset_name": "Deal Flow Network — Pipeline de Investimentos",
    "asset_type": "strategic_non_recognized",
    "asset_class": "network_value",
    "asset_subclass": "Relacionamentos com fundadores, VCs e aceleradoras",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "AWQ Venture Investimentos",
    "custodian_responsible": "Gestor AWQ Venture",
    "acquisition_date": "2023-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": false,
    "is_shared_with_other_bus": false,
    "funding_source": "Construção orgânica",
    "allocation_rule": null,
    "documentation_status": "missing",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "Gestor AWQ Venture",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Pipeline de deals. Não mensurável contabilmente mas crítico para geração de retorno."
  },
  {
    "asset_id": "VEN-STR-002",
    "holding_id": "AWQ",
    "bu_id": "venture",
    "asset_name": "Tese de Investimento e Posição Estratégica do Grupo",
    "asset_type": "strategic_non_recognized",
    "asset_class": "strategic_position",
    "asset_subclass": "Framework de alocação e sinergias entre BUs do grupo",
    "recognition_type": "strategic_non_recognized",
    "ownership_type": "owned",
    "owner_entity": "AWQ Venture Investimentos",
    "custodian_responsible": "Gestor AWQ Venture",
    "acquisition_date": "2023-01-01",
    "activation_date": null,
    "acquisition_cost": 0,
    "replacement_cost": null,
    "residual_value": 0,
    "useful_life_months": 0,
    "depreciation_method": "not_applicable",
    "amortization_method": "not_applicable",
    "monthly_depreciation": 0,
    "monthly_amortization": 0,
    "gross_book_value": 0,
    "accumulated_depreciation": 0,
    "accumulated_amortization": 0,
    "carrying_value": 0,
    "impairment_flag": false,
    "impairment_amount": 0,
    "status": "active",
    "location": "Estratégico — não físico",
    "is_shared_with_holding": true,
    "is_shared_with_other_bus": true,
    "funding_source": "Desenvolvimento interno",
    "allocation_rule": "50% AWQ Venture / 30% AWQ Holding / 20% distribuído entre BUs operacionais",
    "documentation_status": "partial",
    "evidence_level": "low",
    "valuation_confidence": "estimated",
    "review_owner": "Gestor AWQ Venture",
    "last_review_date": "2026-01-01",
    "next_review_date": "2026-12-31",
    "notes": "Tese viva. Atualizada a cada ciclo de alocação de capital."
  }
];


// ─── Subledger exports ────────────────────────────────────────────────────────

export const jacqesSubledger: BuAssetSubledger = {
  bu_id: "jacqes",
  bu_name: "JACQES",
  snapshot_date: "2026-03-31",
  period: "2026-Q1",
  assets: jacqesAssets,
  movements: [],
  utilization: [],
  links: [],
  reviews: [],
};

export const cazaSubledger: BuAssetSubledger = {
  bu_id: "caza",
  bu_name: "Caza Vision",
  snapshot_date: "2026-03-31",
  period: "2026-Q1",
  assets: cazaAssets,
  movements: [],
  utilization: [],
  links: [],
  reviews: [],
};

export const advisorSubledger: BuAssetSubledger = {
  bu_id: "advisor",
  bu_name: "Advisor",
  snapshot_date: "2026-03-31",
  period: "2026-Q1",
  assets: advisorAssets,
  movements: [],
  utilization: [],
  links: [],
  reviews: [],
};

export const ventureSubledger: BuAssetSubledger = {
  bu_id: "venture",
  bu_name: "AWQ Venture",
  snapshot_date: "2026-03-31",
  period: "2026-Q1",
  assets: ventureAssets,
  movements: [],
  utilization: [],
  links: [],
  reviews: [],
};

/** All BU subledgers — consumed exclusively by lib/asset-query.ts */
export const ALL_BU_SUBLEDGERS: BuAssetSubledger[] = [
  jacqesSubledger,
  cazaSubledger,
  advisorSubledger,
  ventureSubledger,
];
