// Client-safe M&A seed data — no server imports.
// Used by client components when NEXT_PUBLIC_STATIC_DATA === "1" (GitHub Pages).

export const SEED_DEALS = [
  {
    deal_id: "deal-2026-001",
    deal_code: "DEAL-2026-001",
    deal_name: "Energdy M4E — Série A",
    company_name: "Grupo Energdy",
    company_website: "https://energdy.com.br",
    industry: "cleantech",
    company_stage: "seed",
    deal_type: "m4e",
    pipeline_stage: "closed_won",
    lead_source: "network",
    market_score: 20,
    team_score: 18,
    product_score: 15,
    traction_score: 12,
    total_score: 65,
    screening_decision: "approved",
    dd_status: "completed",
    dd_completion_pct: 100,
    proposed_valuation: 1000000,
    proposed_investment_amount: null,
    proposed_equity_pct: 20,
    media_commitment_value: 200000,
    ic_decision: "approved",
    ic_decision_date: "2026-02-28",
    actual_close_date: "2026-03-01",
    close_reason: null,
    portco_id: "portco-2026-001",
    deal_lead: "Miguel (AWQ)",
    created_at: "2025-12-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
];

export const SEED_PORTCOS = [
  {
    portco_id: "portco-2026-001",
    portco_code: "PORTCO-2026-001",
    legal_name: "Grupo Energdy Ltda.",
    trade_name: "Energdy",
    deal_id: "deal-2026-001",
    deal_type: "m4e",
    investment_date: "2026-03-01",
    awq_ownership_pct: 20,
    awq_shares_held: 200000,
    total_shares_outstanding: 1000000,
    entry_valuation: 1000000,
    current_valuation: 1050000,
    media_commitment_value: 200000,
    media_delivered_value: 24000,
    media_remaining_value: 176000,
    status: "active",
    industry: "cleantech",
    sector: "energia renovável",
    ceo_name: "Rodrigo Energdy",
    ceo_email: "rodrigo@energdy.com.br",
    website: "https://energdy.com.br",
    unrealized_gain: 50000,
    valuation_multiple: 1.05,
    media_delivery_pct: 12,
    latest_mrr: 11200,
    latest_arr: 134400,
    latest_burn: -19500,
    latest_runway: 8.2,
    latest_mom_growth: 31.76,
    latest_headcount: 5,
    kpi_as_of: "2026-04-30",
  },
];

export const SEED_KPIS = [
  {
    kpi_id: "kpi-001",
    portco_id: "portco-2026-001",
    reporting_date: "2026-03-31",
    year_month: "2026-03",
    mrr: 8500,
    arr: 102000,
    total_revenue: 8500,
    gross_margin_pct: 62,
    burn_rate: -22000,
    cash_balance: 180000,
    runway_months: 8.2,
    mom_growth_pct: null,
    headcount: 4,
    notes: "Primeiro mês pós-fechamento do deal.",
  },
  {
    kpi_id: "kpi-002",
    portco_id: "portco-2026-001",
    reporting_date: "2026-04-30",
    year_month: "2026-04",
    mrr: 11200,
    arr: 134400,
    total_revenue: 11200,
    gross_margin_pct: 65,
    burn_rate: -19500,
    cash_balance: 160500,
    runway_months: 8.2,
    mom_growth_pct: 31.76,
    headcount: 5,
    notes: "Crescimento MoM de 31.76%.",
  },
];

export const SEED_CAP_TABLE = [
  {
    cap_table_id: "ct-001",
    portco_id: "portco-2026-001",
    shareholder_name: "Fundadores Energdy",
    shareholder_type: "founder",
    shareholder_entity: "Grupo Energdy Fundadores Ltda.",
    share_class: "common",
    shares_held: 700000,
    ownership_pct: 70,
    vesting_schedule: null,
    vesting_start_date: null,
    vesting_cliff_date: null,
    vesting_end_date: null,
    shares_vested: 700000,
    shares_unvested: 0,
    cost_per_share: null,
    total_cost_basis: null,
    acquisition_date: "2026-03-01",
    is_active: true,
  },
  {
    cap_table_id: "ct-002",
    portco_id: "portco-2026-001",
    shareholder_name: "AWQ Group",
    shareholder_type: "investor",
    shareholder_entity: "AWQ Group S.A.",
    share_class: "preferred",
    shares_held: 200000,
    ownership_pct: 20,
    vesting_schedule: "4 anos com cliff de 1 ano",
    vesting_start_date: "2026-03-01",
    vesting_cliff_date: "2027-03-01",
    vesting_end_date: "2030-03-01",
    shares_vested: 0,
    shares_unvested: 200000,
    cost_per_share: null,
    total_cost_basis: null,
    acquisition_date: "2026-03-01",
    is_active: true,
  },
  {
    cap_table_id: "ct-003",
    portco_id: "portco-2026-001",
    shareholder_name: "Angels Round",
    shareholder_type: "investor",
    shareholder_entity: null,
    share_class: "common",
    shares_held: 100000,
    ownership_pct: 10,
    vesting_schedule: null,
    vesting_start_date: null,
    vesting_cliff_date: null,
    vesting_end_date: null,
    shares_vested: 100000,
    shares_unvested: 0,
    cost_per_share: null,
    total_cost_basis: null,
    acquisition_date: "2026-03-01",
    is_active: true,
  },
];

export const SEED_BOARD_MEETINGS = [
  {
    meeting_id: "bm-001",
    portco_id: "portco-2026-001",
    meeting_date: "2026-04-10",
    meeting_type: "monthly_review",
    agenda: "1. KPIs Mar/26 | 2. Execução de mídia JACQES | 3. Pipeline de clientes | 4. Runway e próximos 90 dias",
    board_deck_url: null,
    financial_report_url: null,
    attendees: ["Rodrigo Energdy", "Miguel (AWQ)", "Danilo (AWQ)"],
    awq_representative: "Miguel (AWQ)",
    minutes_url: null,
    resolutions: [{ resolution: "Aprovação do orçamento Q2 2026", vote: "unanimous" }],
    action_items: [
      { item: "Enviar cronograma de entregas de mídia para Abr/26", owner: "Miguel (AWQ)", due: "2026-04-15" },
      { item: "Atualizar projeção de runway com burn atualizado", owner: "Rodrigo Energdy", due: "2026-04-20" },
    ],
    status: "completed",
    notes: "Reunião produtiva. Crescimento alinhado com projeções do IC.",
  },
];

export const SEED_MEDIA_DELIVERABLES = [
  {
    deliverable_id: "md-001",
    portco_id: "portco-2026-001",
    deliverable_type: "social_media",
    description: "Gestão de redes sociais Energdy — Março 2026 (Instagram + LinkedIn)",
    agreed_value: 8000,
    executing_bu: "JACQES",
    project_ref: "JACQ-ENE-MAR26",
    scheduled_delivery_date: "2026-03-31",
    actual_delivery_date: "2026-03-31",
    status: "approved",
    approved_by_portco: true,
    approval_date: "2026-04-02",
    approval_notes: "Aprovado pelo CEO Rodrigo via e-mail.",
    deliverable_url: null,
  },
  {
    deliverable_id: "md-002",
    portco_id: "portco-2026-001",
    deliverable_type: "social_media",
    description: "Gestão de redes sociais Energdy — Abril 2026 (Instagram + LinkedIn)",
    agreed_value: 8000,
    executing_bu: "JACQES",
    project_ref: "JACQ-ENE-ABR26",
    scheduled_delivery_date: "2026-04-30",
    actual_delivery_date: "2026-04-30",
    status: "approved",
    approved_by_portco: true,
    approval_date: "2026-05-03",
    approval_notes: "Aprovado pelo CEO Rodrigo via WhatsApp.",
    deliverable_url: null,
  },
  {
    deliverable_id: "md-003",
    portco_id: "portco-2026-001",
    deliverable_type: "video_production",
    description: "Vídeo institucional Energdy — cases residenciais energia solar",
    agreed_value: 35000,
    executing_bu: "CAZA",
    project_ref: "CAZA-ENE-VID01",
    scheduled_delivery_date: "2026-05-31",
    actual_delivery_date: null,
    status: "in_progress",
    approved_by_portco: false,
    approval_date: null,
    approval_notes: null,
    deliverable_url: null,
  },
];

export const SEED_IC_MEETINGS = [
  {
    ic_meeting_id: "icm-001",
    meeting_date: "2026-02-28",
    meeting_type: "deal_review",
    attendees: ["Miguel (AWQ)", "Danilo (AWQ)", "Conselheiro Externo A", "Conselheiro Externo B"],
    deals_reviewed: ["deal-2026-001"],
    minutes_url: null,
    status: "completed",
    decisions: [
      {
        ic_decision_id: "icd-001",
        deal_id: "deal-2026-001",
        decision: "approved",
        decision_date: "2026-02-28",
        vote_result: "unanimous",
        decision_rationale: "Mercado endereçável grande com tailwinds regulatórios.",
        conditions: "Entrega trimestral de KPIs. Relatórios financeiros mensais ao observer AWQ.",
      },
    ],
    created_at: "2026-02-28T00:00:00Z",
  },
];

export const SEED_SYNERGIES = [
  {
    synergy_id: "syn-001",
    synergy_type: "cross_selling",
    opportunity_name: "JACQES × Energdy — Clientes em comum",
    description: "Clientes corporativos do JACQES com alta pegada de carbono podem ser referenciados para soluções de compensação via Energdy.",
    source_bu: "JACQES",
    target_bu: null,
    portco_id: "portco-2026-001",
    estimated_revenue_impact: 200000,
    estimated_cost_savings: null,
    status: "in_progress",
    identified_date: "2026-03-15",
    realization_date: null,
    actual_revenue_impact: null,
    actual_cost_savings: null,
    owner: "Miguel (AWQ)",
    notes: "Mapeamento de base de clientes JACQES concluído.",
  },
];

export const SEED_INTERCOMPANY = [
  {
    ic_transaction_id: "ict-001",
    transaction_date: "2026-03-31",
    transaction_type: "media_delivery",
    from_entity_name: "JACQES",
    to_entity_name: "Grupo Energdy",
    amount: 8000,
    elimination_status: "eliminated",
    description: "Entrega de mídia — Social Media Mar/26 — JACQ-ENE-MAR26",
  },
  {
    ic_transaction_id: "ict-002",
    transaction_date: "2026-04-30",
    transaction_type: "media_delivery",
    from_entity_name: "JACQES",
    to_entity_name: "Grupo Energdy",
    amount: 8000,
    elimination_status: "eliminated",
    description: "Entrega de mídia — Social Media Abr/26 — JACQ-ENE-ABR26",
  },
];

export const SEED_CONSOLIDATED = {
  equity_portfolio: {
    total_invested: 1000000,
    total_current_value: 1050000,
    unrealized_gain: 50000,
    avg_multiple: 1.05,
  },
  intercompany: {
    total_transactions: 2,
    total_eliminated: 2,
    pending_elimination: 0,
  },
  media_obligations: {
    total_committed: 200000,
    total_delivered: 24000,
    total_remaining: 176000,
    delivery_pct: 12,
  },
};

export function computePortfolioTotals(portcos: typeof SEED_PORTCOS) {
  const total_portcos        = portcos.length;
  const active_portcos       = portcos.filter(p => p.status === "active").length;
  const total_investment     = portcos.reduce((s, p) => s + (p.entry_valuation ?? 0), 0);
  const total_current_value  = portcos.reduce((s, p) => s + (p.current_valuation ?? 0), 0);
  const total_unrealized_gain = total_current_value - total_investment;
  const weighted_avg_multiple = total_investment > 0 ? total_current_value / total_investment : 0;
  const total_media_committed = portcos.reduce((s, p) => s + (p.media_commitment_value ?? 0), 0);
  const total_media_delivered = portcos.reduce((s, p) => s + (p.media_delivered_value ?? 0), 0);
  const media_delivery_pct   = total_media_committed > 0
    ? (total_media_delivered / total_media_committed) * 100 : 0;
  return {
    total_portcos, active_portcos, total_investment, total_current_value,
    total_unrealized_gain, weighted_avg_multiple,
    total_media_committed, total_media_delivered, media_delivery_pct,
  };
}
