// ─── AWQ Cyber Security Core — Security Registry ────────────────────────────
// Every finding here is based on actual analysis of the AWQ repository.
// Trust levels reflect what the codebase allows us to verify.

import type {
  DataSourceAudit,
  SecretAudit,
  AccessAudit,
  SecurityRisk,
  MonitoringCapability,
  SecurityAction,
} from "./types";

// ── Data Source Audit Registry ───────────────────────────────────────────────
// Mapped from actual files: lib/data.ts, lib/awq-group-data.ts, lib/caza-data.ts,
// pages/api/*, components/OpenClawWidget.tsx, components/SupervisorWidget.tsx

export const dataSourceRegistry: DataSourceAudit[] = [
  {
    id: "DS001",
    name: "JACQES KPIs & Financial Data",
    type: "static_file",
    bu: "JACQES",
    module: "Dashboard / Financial / Unit Economics",
    filePath: "lib/data.ts",
    hasExternalDependency: false,
    requiresSecret: false,
    secretExposed: false,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "Dados estáticos hardcoded. Sem risco de exposição de segredo, mas sem fonte de verdade externa verificável.",
  },
  {
    id: "DS002",
    name: "AWQ Group Consolidated Data",
    type: "static_file",
    bu: "AWQ",
    module: "Control Tower / Visão Geral",
    filePath: "lib/awq-group-data.ts",
    hasExternalDependency: false,
    requiresSecret: false,
    secretExposed: false,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "Dados de holding consolidados estaticamente. Alterações requerem deploy.",
  },
  {
    id: "DS003",
    name: "Caza Vision Project & Client Data",
    type: "static_file",
    bu: "Caza Vision",
    module: "Dashboard / Projetos / Clientes",
    filePath: "lib/caza-data.ts",
    hasExternalDependency: false,
    requiresSecret: false,
    secretExposed: false,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "Dados estáticos de projetos imobiliários e clientes. Sem dependência externa.",
  },
  {
    id: "DS004",
    name: "Notion Database Integration",
    type: "notion_api",
    bu: "JACQES",
    module: "API Routes / Data Sync",
    filePath: "pages/api/notion/*.ts",
    hasExternalDependency: true,
    requiresSecret: true,
    secretExposed: false,
    hasFallback: true,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "Integração com Notion via API key server-side. Dependência externa real. API key protegida por env var.",
  },
  {
    id: "DS005",
    name: "OpenClaw AI Chat — Anthropic API",
    type: "external_api",
    bu: "AWQ",
    module: "OpenClaw Widget / Chat",
    filePath: "components/OpenClawWidget.tsx",
    hasExternalDependency: true,
    requiresSecret: true,
    secretExposed: true,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "RISCO: Widget permite input de API key pelo usuário via localStorage. A key fica armazenada no client-side sem encriptação.",
  },
  {
    id: "DS006",
    name: "Supervisor Agent — Anthropic API",
    type: "external_api",
    bu: "AWQ",
    module: "Supervisor Widget",
    filePath: "components/SupervisorWidget.tsx",
    hasExternalDependency: true,
    requiresSecret: true,
    secretExposed: false,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "probable",
    riskNotes: "Supervisor utiliza API routes server-side. API key via env var. Análise de exposição depende de verificação de runtime.",
  },
  {
    id: "DS007",
    name: "NextAuth JWT Session",
    type: "session_jwt",
    bu: "AWQ",
    module: "Autenticação / Sessão",
    filePath: "pages/api/auth/[...nextauth].ts",
    hasExternalDependency: false,
    requiresSecret: true,
    secretExposed: false,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "JWT session com NEXTAUTH_SECRET. Estratégia de sessão adequada. Secret deve ser rotacionado periodicamente.",
  },
  {
    id: "DS008",
    name: "User Database — In-Memory",
    type: "static_file",
    bu: "AWQ",
    module: "Autenticação",
    filePath: "lib/auth-users.ts",
    hasExternalDependency: false,
    requiresSecret: false,
    secretExposed: false,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "Usuários e password hashes hardcoded em arquivo. Senhas usam bcrypt (seguro), mas o modelo in-memory não escala e hashes ficam no bundle.",
  },
  {
    id: "DS009",
    name: "Agent Configurations",
    type: "static_file",
    bu: "AWQ",
    module: "Agents / IA",
    filePath: "lib/agents-config.ts",
    hasExternalDependency: false,
    requiresSecret: false,
    secretExposed: false,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "Configurações de agentes IA. Sem segredos. Prompts de sistema expostos no client bundle.",
  },
  {
    id: "DS010",
    name: "localStorage — API Keys & State",
    type: "localStorage",
    bu: "AWQ",
    module: "OpenClaw / Supervisor Widgets",
    filePath: "components/OpenClawWidget.tsx",
    hasExternalDependency: false,
    requiresSecret: false,
    secretExposed: true,
    hasFallback: false,
    fallbackInsecure: false,
    hasMockData: false,
    mockInProduction: false,
    trustLevel: "confirmed",
    riskNotes: "RISCO: API keys armazenadas em localStorage sem encriptação. Qualquer script no mesmo domínio pode acessar.",
  },
];

// ── Secret Audit Registry ────────────────────────────────────────────────────

export const secretRegistry: SecretAudit[] = [
  {
    id: "SEC001",
    name: "NEXTAUTH_SECRET",
    type: "auth_secret",
    envVariable: "NEXTAUTH_SECRET",
    usedInFiles: ["pages/api/auth/[...nextauth].ts"],
    serverOnly: true,
    exposureRisk: "server_only",
    rotationPolicy: "not_available",
    trustLevel: "confirmed",
    notes: "Segredo JWT usado para assinar tokens de sessão. Server-only. Não há política de rotação configurada.",
  },
  {
    id: "SEC002",
    name: "ANTHROPIC_API_KEY",
    type: "api_key",
    envVariable: "ANTHROPIC_API_KEY",
    usedInFiles: ["app/api/chat/route.ts", "app/api/agents/route.ts", "app/api/supervisor/route.ts"],
    serverOnly: true,
    exposureRisk: "server_only",
    rotationPolicy: "not_available",
    trustLevel: "confirmed",
    notes: "API key da Anthropic para agentes IA. Usada em API routes server-side. Protegida por env var.",
  },
  {
    id: "SEC003",
    name: "NOTION_API_KEY",
    type: "api_key",
    envVariable: "NOTION_API_KEY",
    usedInFiles: ["pages/api/notion/query.ts"],
    serverOnly: true,
    exposureRisk: "server_only",
    rotationPolicy: "not_available",
    trustLevel: "confirmed",
    notes: "API key do Notion para leitura de databases. Server-only via API routes.",
  },
  {
    id: "SEC004",
    name: "NOTION_DATABASE_IDs",
    type: "database_id",
    envVariable: "NOTION_DATABASE_ID_*",
    usedInFiles: ["pages/api/notion/query.ts"],
    serverOnly: true,
    exposureRisk: "server_only",
    rotationPolicy: "not_available",
    trustLevel: "confirmed",
    notes: "IDs de databases Notion. Não são segredos sensíveis por si só, mas revelam estrutura interna.",
  },
  {
    id: "SEC005",
    name: "User Password Hashes (bcrypt)",
    type: "password_hash",
    envVariable: "N/A — hardcoded",
    usedInFiles: ["lib/auth-users.ts"],
    serverOnly: false,
    exposureRisk: "hardcoded",
    rotationPolicy: "not_available",
    trustLevel: "confirmed",
    notes: "RISCO: Password hashes bcrypt hardcoded no código-fonte. Embora bcrypt seja seguro, os hashes ficam no bundle e no repositório.",
  },
  {
    id: "SEC006",
    name: "Client-side API Key (OpenClaw)",
    type: "api_key",
    envVariable: "N/A — localStorage",
    usedInFiles: ["components/OpenClawWidget.tsx"],
    serverOnly: false,
    exposureRisk: "client_risk",
    rotationPolicy: "not_available",
    trustLevel: "confirmed",
    notes: "RISCO: Usuários podem inserir API keys diretamente no widget. Armazenada em localStorage sem encriptação.",
  },
];

// ── Access & Authentication Audit ────────────────────────────────────────────

export const accessRegistry: AccessAudit[] = [
  {
    id: "ACC001",
    area: "Middleware RBAC",
    description: "Middleware de autenticação via NextAuth withAuth",
    hasAuthentication: true,
    hasAuthorization: true,
    rbacEnforced: false,
    buIsolation: false,
    trustLevel: "confirmed",
    severity: "medium",
    notes: "RBAC definido mas não efetivo: todos os roles têm acesso a '/' (acesso total). Não há segregação real entre BUs.",
  },
  {
    id: "ACC002",
    area: "API Routes — Auth",
    description: "Rotas de API para chat, agents, supervisor, notion",
    hasAuthentication: false,
    hasAuthorization: false,
    rbacEnforced: false,
    buIsolation: false,
    trustLevel: "confirmed",
    severity: "high",
    notes: "RISCO: API routes não verificam sessão/token. Qualquer request pode acessar /api/chat, /api/agents, /api/supervisor sem autenticação.",
  },
  {
    id: "ACC003",
    area: "Isolamento de Dados entre BUs",
    description: "Separação de dados financeiros e operacionais entre BUs",
    hasAuthentication: true,
    hasAuthorization: false,
    rbacEnforced: false,
    buIsolation: false,
    trustLevel: "confirmed",
    severity: "medium",
    notes: "Dados de todas as BUs são carregados em arquivos estáticos compartilhados. Qualquer usuário autenticado vê dados de todas as BUs.",
  },
  {
    id: "ACC004",
    area: "Sessão & Roles",
    description: "4 roles definidos: owner, admin, analyst, cs-ops",
    hasAuthentication: true,
    hasAuthorization: true,
    rbacEnforced: false,
    buIsolation: false,
    trustLevel: "confirmed",
    severity: "low",
    notes: "Roles existem na sessão JWT mas ROLE_ALLOWED_PREFIXES dá '/' para todos. Infraestrutura pronta mas não ativada.",
  },
  {
    id: "ACC005",
    area: "Login & Password",
    description: "Autenticação por email/senha com bcrypt",
    hasAuthentication: true,
    hasAuthorization: false,
    rbacEnforced: false,
    buIsolation: false,
    trustLevel: "confirmed",
    severity: "info",
    notes: "Login funcional com bcrypt. Base de usuários in-memory (4 usuários). Adequado para fase atual, não escala.",
  },
];

// ── Risk Register ────────────────────────────────────────────────────────────

export const riskRegister: SecurityRisk[] = [
  {
    id: "RISK001",
    title: "API Routes sem Autenticação",
    description: "As rotas /api/chat, /api/agents e /api/supervisor não verificam sessão NextAuth. Qualquer request externo pode invocar a API da Anthropic usando a key do servidor.",
    category: "missing_auth",
    severity: "high",
    status: "open",
    bu: "AWQ",
    module: "API Routes",
    evidence: "middleware.ts exclui /api/ do RBAC (linha 15). API routes não importam getServerSession.",
    trustLevel: "confirmed",
    recommendation: "Adicionar verificação de sessão NextAuth em todas as API routes. Usar getServerSession() no início de cada handler.",
    impact: "Uso não autorizado da API key Anthropic. Custo financeiro e risco de abuso.",
    owner: "Platform Engineering",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK002",
    title: "API Key em localStorage sem Encriptação",
    description: "O OpenClawWidget permite que usuários insiram API keys diretamente. Estas são armazenadas em localStorage sem qualquer encriptação.",
    category: "credential_exposure",
    severity: "high",
    status: "open",
    bu: "AWQ",
    module: "OpenClaw Widget",
    evidence: "components/OpenClawWidget.tsx — localStorage.setItem para API key",
    trustLevel: "confirmed",
    recommendation: "Remover input de API key do client-side. Usar exclusivamente API routes server-side com a key em env var.",
    impact: "Qualquer script XSS ou extensão de browser pode extrair a API key do localStorage.",
    owner: "Platform Engineering",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK003",
    title: "Password Hashes Hardcoded no Código",
    description: "Os hashes bcrypt dos usuários estão definidos diretamente em lib/auth-users.ts, incluídos no bundle de produção e visíveis no repositório.",
    category: "credential_exposure",
    severity: "medium",
    status: "open",
    bu: "AWQ",
    module: "Autenticação",
    evidence: "lib/auth-users.ts — hashes bcrypt inline",
    trustLevel: "confirmed",
    recommendation: "Mover para banco de dados ou serviço de autenticação externo. Em curto prazo, garantir que o arquivo não seja incluído no client bundle.",
    impact: "Hashes expostos no repositório. Embora bcrypt seja resistente, a exposição desnecessária é um risco de governança.",
    owner: "Platform Engineering",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK004",
    title: "RBAC Definido mas Não Efetivo",
    description: "O sistema ROLE_ALLOWED_PREFIXES existe, mas todos os roles têm acesso a '/', tornando a segregação inoperante.",
    category: "access_control",
    severity: "medium",
    status: "open",
    bu: "AWQ",
    module: "Middleware / Auth",
    evidence: "lib/auth-users.ts — ROLE_ALLOWED_PREFIXES: todos com ['/']",
    trustLevel: "confirmed",
    recommendation: "Restringir prefixos por role. Ex: analyst → ['/jacqes'], cs-ops → ['/csops', '/jacqes'].",
    impact: "Qualquer usuário autenticado acessa qualquer BU e módulo da plataforma.",
    owner: "Security / Platform",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK005",
    title: "Sem Isolamento de Dados entre BUs",
    description: "Dados financeiros de todas as BUs (JACQES, Caza Vision, Advisor, Venture) são carregados em arquivos estáticos compartilhados e acessíveis a qualquer usuário.",
    category: "bu_isolation",
    severity: "medium",
    status: "open",
    bu: "AWQ",
    module: "Data Layer",
    evidence: "lib/awq-group-data.ts, lib/data.ts, lib/caza-data.ts — todos importados sem filtro por role/BU",
    trustLevel: "confirmed",
    recommendation: "Para dados estáticos, aceitar risco na fase atual. Para dados dinâmicos futuros, implementar filtro server-side por BU baseado no role do usuário.",
    impact: "Um analista da JACQES pode ver dados financeiros da Caza Vision e vice-versa.",
    owner: "Security / Platform",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK006",
    title: "Prompts de Sistema Expostos no Client Bundle",
    description: "Configurações de agentes IA, incluindo system prompts, são definidas em lib/agents-config.ts e podem ser incluídas no bundle client-side.",
    category: "data_exposure",
    severity: "low",
    status: "open",
    bu: "AWQ",
    module: "Agents / IA",
    evidence: "lib/agents-config.ts — configurações de agentes em arquivo compartilhado",
    trustLevel: "probable",
    recommendation: "Mover configurações de agentes para API routes server-side ou variáveis de ambiente.",
    impact: "Exposição de lógica de negócio e instruções de agentes IA. Risco de engenharia reversa.",
    owner: "Platform Engineering",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK007",
    title: "Dependência Externa — Notion API",
    description: "Integração com Notion para dados operacionais. Falha na API do Notion pode impactar funcionalidades da plataforma.",
    category: "dependency_risk",
    severity: "low",
    status: "open",
    bu: "JACQES",
    module: "Notion Integration",
    evidence: "pages/api/notion/ — chamadas à API do Notion",
    trustLevel: "confirmed",
    recommendation: "Implementar cache local e fallback para dados Notion. Monitorar disponibilidade da API.",
    impact: "Indisponibilidade de dados operacionais se Notion ficar fora do ar.",
    owner: "Platform Engineering",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK008",
    title: "Dependência Externa — Anthropic API",
    description: "Funcionalidades de IA (OpenClaw, Supervisor, Agents) dependem 100% da API da Anthropic sem fallback.",
    category: "dependency_risk",
    severity: "low",
    status: "accepted",
    bu: "AWQ",
    module: "IA & Agentes",
    evidence: "app/api/chat/route.ts, app/api/agents/route.ts, app/api/supervisor/route.ts",
    trustLevel: "confirmed",
    recommendation: "Aceitar risco para funcionalidades de IA. Implementar graceful degradation com mensagem ao usuário em caso de falha.",
    impact: "Funcionalidades de IA ficam indisponíveis se a API da Anthropic falhar.",
    owner: "Platform Engineering",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK009",
    title: "Sem Política de Rotação de Segredos",
    description: "Nenhum dos segredos (NEXTAUTH_SECRET, ANTHROPIC_API_KEY, NOTION_API_KEY) tem política de rotação definida.",
    category: "governance",
    severity: "medium",
    status: "open",
    bu: "AWQ",
    module: "Infraestrutura",
    evidence: "Ausência de documentação ou automação de rotação de secrets",
    trustLevel: "confirmed",
    recommendation: "Definir política de rotação trimestral. Documentar processo de rotação para cada segredo.",
    impact: "Segredos comprometidos permanecem válidos indefinidamente.",
    owner: "Security / Infra",
    createdAt: "2026-04-02",
  },
  {
    id: "RISK010",
    title: "GitHub Pages — Deploy Público",
    description: "A plataforma é publicada via GitHub Pages (contato22.github.io/awq). Todo o bundle JavaScript é publicamente acessível.",
    category: "configuration",
    severity: "medium",
    status: "accepted",
    bu: "AWQ",
    module: "Deploy / Publicação",
    evidence: "next.config.mjs — STATIC_EXPORT=1, GitHub Pages como destino",
    trustLevel: "confirmed",
    recommendation: "Garantir que nenhum segredo, hash ou dado sensível seja incluído no client bundle. Considerar deploy privado para produção.",
    impact: "Bundle JS acessível publicamente. Dados estáticos, configurações e hashes expostos.",
    owner: "Platform Engineering",
    createdAt: "2026-04-02",
  },
];

// ── Monitoring Capabilities ──────────────────────────────────────────────────

export const monitoringCapabilities: MonitoringCapability[] = [
  {
    id: "MON001",
    name: "Autenticação de Sessão",
    description: "Verificação de sessão JWT em cada request via middleware NextAuth",
    state: "active",
    category: "real_time",
    notes: "Middleware ativo em todas as rotas (exceto /api). Sessões expiram conforme config JWT.",
  },
  {
    id: "MON002",
    name: "Supervisor Agent — Alertas",
    description: "Agente autônomo que monitora métricas e gera alertas",
    state: "configured",
    category: "periodic",
    notes: "SupervisorWidget implementado mas depende de ativação manual pelo usuário. Não é monitoramento 24h real.",
  },
  {
    id: "MON003",
    name: "Auditoria de Acesso por Role",
    description: "Logging e auditoria de quem acessou o quê",
    state: "not_available",
    category: "planned",
    notes: "Infraestrutura de roles existe mas não há logging de acessos. Necessário para compliance.",
  },
  {
    id: "MON004",
    name: "Detecção de Segredos Expostos",
    description: "Scan automatizado do repositório para segredos hardcoded",
    state: "not_available",
    category: "planned",
    notes: "Não há integração com ferramentas como GitGuardian, TruffleHog ou GitHub Secret Scanning.",
  },
  {
    id: "MON005",
    name: "Monitoramento de Dependências",
    description: "Verificação de vulnerabilidades em dependências npm",
    state: "not_available",
    category: "planned",
    notes: "Não há Dependabot, Snyk ou npm audit automatizado configurado no CI.",
  },
  {
    id: "MON006",
    name: "Monitoramento de Disponibilidade",
    description: "Uptime monitoring da plataforma publicada",
    state: "not_available",
    category: "planned",
    notes: "Não há UptimeRobot, Pingdom ou similar configurado.",
  },
  {
    id: "MON007",
    name: "Incident Response Readiness",
    description: "Procedimentos e runbooks para resposta a incidentes",
    state: "planned",
    category: "manual",
    notes: "Este módulo de Cyber Security é o primeiro passo. Runbooks e procedimentos ainda precisam ser criados.",
  },
];

// ── Security Action Queue ────────────────────────────────────────────────────

export const actionQueue: SecurityAction[] = [
  {
    id: "ACT001",
    title: "Proteger API Routes com Autenticação",
    description: "Adicionar getServerSession() em /api/chat, /api/agents, /api/supervisor. Rejeitar requests sem sessão válida.",
    priority: "p0_immediate",
    severity: "high",
    relatedRiskId: "RISK001",
    suggestedOwner: "Platform Engineering",
    estimatedEffort: "small",
    status: "open",
  },
  {
    id: "ACT002",
    title: "Remover API Key Input do Client-Side",
    description: "Eliminar a funcionalidade de input de API key no OpenClawWidget. Usar exclusivamente a API route server-side.",
    priority: "p0_immediate",
    severity: "high",
    relatedRiskId: "RISK002",
    suggestedOwner: "Platform Engineering",
    estimatedEffort: "medium",
    status: "open",
  },
  {
    id: "ACT003",
    title: "Ativar RBAC Real nos Prefixos",
    description: "Configurar ROLE_ALLOWED_PREFIXES com restrições reais por role. Testar que analyst não acessa /awq, cs-ops não acessa /caza-vision, etc.",
    priority: "p1_urgent",
    severity: "medium",
    relatedRiskId: "RISK004",
    suggestedOwner: "Security / Platform",
    estimatedEffort: "small",
    status: "open",
  },
  {
    id: "ACT004",
    title: "Externalizar User Database",
    description: "Mover usuários e hashes para env vars, banco de dados ou serviço externo de auth. Remover hashes do código-fonte.",
    priority: "p1_urgent",
    severity: "medium",
    relatedRiskId: "RISK003",
    suggestedOwner: "Platform Engineering",
    estimatedEffort: "medium",
    status: "open",
  },
  {
    id: "ACT005",
    title: "Definir Política de Rotação de Segredos",
    description: "Criar runbook de rotação para NEXTAUTH_SECRET, ANTHROPIC_API_KEY e NOTION_API_KEY. Definir cadência trimestral.",
    priority: "p2_standard",
    severity: "medium",
    relatedRiskId: "RISK009",
    suggestedOwner: "Security / Infra",
    estimatedEffort: "small",
    status: "open",
  },
  {
    id: "ACT006",
    title: "Habilitar GitHub Secret Scanning",
    description: "Ativar GitHub Secret Scanning e/ou integrar GitGuardian no repositório para detecção de segredos expostos.",
    priority: "p2_standard",
    severity: "medium",
    relatedRiskId: "RISK010",
    suggestedOwner: "Platform Engineering",
    estimatedEffort: "small",
    status: "open",
  },
  {
    id: "ACT007",
    title: "Mover Agent Configs para Server-Side",
    description: "Transferir lib/agents-config.ts para API routes, evitando exposição de system prompts no client bundle.",
    priority: "p3_improvement",
    severity: "low",
    relatedRiskId: "RISK006",
    suggestedOwner: "Platform Engineering",
    estimatedEffort: "small",
    status: "open",
  },
];
